import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Legacy tokens (kept for backward compat)
        f1red: "#E10600",
        f1black: "#15151E",
        // Stitch design system
        "primary": "#ffb3af",
        "primary-container": "#e8002d",
        "on-primary": "#68000e",
        "on-primary-container": "#fffaf9",
        "primary-fixed": "#ffdad7",
        "primary-fixed-dim": "#ffb3af",
        "on-primary-fixed": "#410006",
        "on-primary-fixed-variant": "#930018",
        "inverse-primary": "#bf0023",
        "secondary": "#c6c6c7",
        "secondary-container": "#454747",
        "on-secondary": "#2f3131",
        "on-secondary-container": "#b4b5b5",
        "secondary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#454747",
        "tertiary": "#29dec9",
        "tertiary-container": "#008275",
        "on-tertiary": "#003731",
        "on-tertiary-container": "#ebfffa",
        "tertiary-fixed": "#56fae5",
        "tertiary-fixed-dim": "#29dec9",
        "on-tertiary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#005048",
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        "surface-tint": "#ffb3af",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#e8bcb9",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "background": "#131313",
        "on-background": "#e5e2e1",
        "outline": "#af8785",
        "outline-variant": "#5e3f3d",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-lg": ["Space Grotesk", "sans-serif"],
        "data-sm": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-base": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "data-lg": ["20px", { lineHeight: "1", letterSpacing: "-0.01em", fontWeight: "700" }],
        "data-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "gutter": "12px",
        "md": "16px",
        "lg": "24px",
        "margin": "24px",
        "xl": "40px",
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "2px",
        md: "4px",
        lg: "8px",
        xl: "12px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
